services:
  wishlist:
    container_name: wishlist
    build: .
    ports:
      - "3000:3000"
    volumes:
      - wishlist-data:/data
    restart: unless-stopped
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.wishlist.rule=HOST('wishlist.xavierchapouille.ddns.net')
      - traefik.http.routers.wishlist.entrypoints=web

volumes:
  wishlist-data:

networks:
  frontend:
    external: true
  backend:
    external: true
